const zh = {
  phone:'手机号', country:'国家或地区', code:'短信验证码', send:'发送验证码', sending:'发送中…',
  login:'短信登录', passwordLogin:'密码登录', retrieve:'短信找回密码', emailRetrieve:'邮箱找回密码',
  register:'注册', username:'用户名', password:'密码', confirm:'确认密码', invite:'邀请码',
  newPassword:'新密码', reset:'重置密码', resetDone:'密码已重置，请重新登录',
  back:'返回登录', unavailable:'当前尚未开通此短信功能', closed:'当前已关闭注册',
  loadError:'无法读取注册设置，请重试', retry:'重试', mismatch:'两次密码输入不一致',
  weak:'密码至少 6 位', failed:'操作失败，请稍后重试', invalidCode:'验证码无效、已过期或已使用',
  rate:'发送过于频繁，请倒计时结束后重试', invalidPhone:'请输入有效的手机号并选择正确的国家或地区',
  unsupported:'当前国家或地区不支持此短信功能', bound:'已绑定手机号', unbound:'未绑定手机号',
  bind:'绑定手机号', unbind:'解绑手机号', bindDone:'手机号已绑定', unbindDone:'手机号已解绑',
  unbindHint:'解绑验证码将发送到当前绑定的手机号，解绑后可使用用户名和密码登录。',
  passwordRequired:'请先设置可用的登录密码再解绑', occupied:'手机号或用户名已被使用', account:'账号不存在或不可用',
  requiredCode:'请先获取并填写短信验证码', submitting:'提交中…', sent:'验证码已发送', inviteRequired:'请输入有效的邀请码'
}
const en = {
  phone:'Phone number',country:'Country or region',code:'SMS code',send:'Send code',sending:'Sending…',login:'SMS login',passwordLogin:'Password login',retrieve:'Reset with SMS',emailRetrieve:'Reset with email',register:'Register',username:'Username',password:'Password',confirm:'Confirm password',invite:'Invitation code',newPassword:'New password',reset:'Reset password',resetDone:'Password reset. Please log in again.',back:'Back to login',unavailable:'This SMS feature is not available yet.',closed:'Registration is closed.',loadError:'Unable to load registration settings.',retry:'Retry',mismatch:'Passwords do not match.',weak:'Use at least 6 characters.',failed:'Unable to complete the request. Please try again.',invalidCode:'The code is invalid, expired or already used.',rate:'Too many requests. Wait before retrying.',invalidPhone:'Enter a valid number and select the correct country.',unsupported:'This SMS feature is unavailable in this country.',bound:'Linked phone',unbound:'No linked phone',bind:'Link phone',unbind:'Unlink phone',bindDone:'Phone linked.',unbindDone:'Phone unlinked.',unbindHint:'The code will be sent to your linked phone. You can still log in with your username and password.',passwordRequired:'Set a login password before unlinking.',occupied:'Phone or username already in use.',account:'Account does not exist or is unavailable.',requiredCode:'Request and enter an SMS code first.',submitting:'Submitting…',sent:'Code sent.',inviteRequired:'Enter a valid invitation code.'
}
const tw = { ...zh, phone:'手機號碼',country:'國家或地區',code:'簡訊驗證碼',send:'發送驗證碼',sending:'發送中…',login:'簡訊登入',passwordLogin:'密碼登入',retrieve:'簡訊找回密碼',emailRetrieve:'郵箱找回密碼',register:'註冊',username:'使用者名稱',password:'密碼',confirm:'確認密碼',invite:'邀請碼',newPassword:'新密碼',reset:'重設密碼',resetDone:'密碼已重設，請重新登入',back:'返回登入',unavailable:'目前尚未開通此簡訊功能',closed:'目前已關閉註冊',loadError:'無法讀取註冊設定，請重試',retry:'重試',mismatch:'兩次密碼輸入不一致',weak:'密碼至少 6 位',failed:'操作失敗，請稍後重試',invalidCode:'驗證碼無效、已過期或已使用',rate:'發送過於頻繁，請倒數結束後重試',invalidPhone:'請輸入有效的手機號碼並選擇正確的國家或地區',unsupported:'目前國家或地區不支援此簡訊功能',bound:'已綁定手機號碼',unbound:'未綁定手機號碼',bind:'綁定手機',unbind:'解綁手機',bindDone:'手機已綁定',unbindDone:'手機已解綁',unbindHint:'驗證碼將發送到目前綁定的手機，解綁後可使用使用者名稱和密碼登入。',passwordRequired:'請先設定可用的登入密碼再解綁',occupied:'手機號碼或使用者名稱已被使用',account:'帳號不存在或不可用',requiredCode:'請先取得並填寫簡訊驗證碼',submitting:'提交中…',sent:'驗證碼已發送',inviteRequired:'請輸入有效的邀請碼' }
const translations = {
  ja: {
    phone:'電話番号',country:'国・地域',code:'SMS認証コード',send:'コードを送信',sending:'送信中…',login:'SMSでログイン',passwordLogin:'パスワードでログイン',retrieve:'SMSでパスワードを再設定',emailRetrieve:'メールでパスワードを再設定',register:'登録',username:'ユーザー名',password:'パスワード',confirm:'パスワードの確認',invite:'招待コード',newPassword:'新しいパスワード',reset:'パスワードを再設定',resetDone:'再設定しました。もう一度ログインしてください。',back:'ログインに戻る',unavailable:'このSMS機能は現在利用できません。',closed:'新規登録は停止中です。',loadError:'登録設定を読み込めません。',retry:'再試行',mismatch:'パスワードが一致しません。',weak:'6文字以上で入力してください。',failed:'操作に失敗しました。後ほど再試行してください。',invalidCode:'コードが無効、期限切れ、または使用済みです。',rate:'送信回数が多すぎます。しばらくお待ちください。',invalidPhone:'有効な電話番号と正しい国・地域を入力してください。',unsupported:'この国・地域では利用できません。',bound:'電話番号は連携済みです',unbound:'電話番号は未連携です',bind:'電話番号を連携',unbind:'連携を解除',bindDone:'電話番号を連携しました。',unbindDone:'連携を解除しました。',unbindHint:'連携済みの電話番号にコードを送信します。解除後もユーザー名とパスワードでログインできます。',passwordRequired:'解除する前にログインパスワードを設定してください。',occupied:'電話番号またはユーザー名は使用済みです。',account:'アカウントが存在しないか利用できません。',requiredCode:'認証コードを取得して入力してください。',submitting:'送信中…',sent:'コードを送信しました。',inviteRequired:'有効な招待コードを入力してください。'
  },
  ko: {
    phone:'휴대폰 번호',country:'국가 또는 지역',code:'문자 인증번호',send:'인증번호 전송',sending:'전송 중…',login:'문자로 로그인',passwordLogin:'비밀번호로 로그인',retrieve:'문자로 비밀번호 찾기',emailRetrieve:'이메일로 비밀번호 찾기',register:'가입',username:'사용자 이름',password:'비밀번호',confirm:'비밀번호 확인',invite:'초대 코드',newPassword:'새 비밀번호',reset:'비밀번호 재설정',resetDone:'비밀번호가 변경되었습니다. 다시 로그인하세요.',back:'로그인으로 돌아가기',unavailable:'현재 이 문자 기능을 사용할 수 없습니다.',closed:'현재 회원가입이 중단되었습니다.',loadError:'가입 설정을 불러올 수 없습니다.',retry:'다시 시도',mismatch:'비밀번호가 일치하지 않습니다.',weak:'6자 이상 입력하세요.',failed:'처리하지 못했습니다. 잠시 후 다시 시도하세요.',invalidCode:'유효하지 않거나 만료 또는 사용된 인증번호입니다.',rate:'요청이 너무 많습니다. 잠시 기다려 주세요.',invalidPhone:'올바른 휴대폰 번호와 국가를 입력하세요.',unsupported:'이 국가에서는 사용할 수 없습니다.',bound:'휴대폰 연결됨',unbound:'연결된 휴대폰 없음',bind:'휴대폰 연결',unbind:'휴대폰 연결 해제',bindDone:'휴대폰이 연결되었습니다.',unbindDone:'연결이 해제되었습니다.',unbindHint:'연결된 휴대폰으로 인증번호를 보냅니다. 해제 후에도 사용자 이름과 비밀번호로 로그인할 수 있습니다.',passwordRequired:'연결 해제 전에 로그인 비밀번호를 설정하세요.',occupied:'이미 사용 중인 휴대폰 번호 또는 사용자 이름입니다.',account:'계정이 없거나 사용할 수 없습니다.',requiredCode:'인증번호를 요청한 후 입력하세요.',submitting:'처리 중…',sent:'인증번호가 전송되었습니다.',inviteRequired:'유효한 초대 코드를 입력하세요.'
  },
  es: {
    phone:'Número de teléfono',country:'País o región',code:'Código SMS',send:'Enviar código',sending:'Enviando…',login:'Entrar por SMS',passwordLogin:'Entrar con contraseña',retrieve:'Restablecer por SMS',emailRetrieve:'Restablecer por correo',register:'Registrarse',username:'Nombre de usuario',password:'Contraseña',confirm:'Confirmar contraseña',invite:'Código de invitación',newPassword:'Nueva contraseña',reset:'Restablecer contraseña',resetDone:'Contraseña restablecida. Inicia sesión de nuevo.',back:'Volver al inicio de sesión',unavailable:'Esta función SMS aún no está disponible.',closed:'El registro está cerrado.',loadError:'No se pudo cargar la configuración de registro.',retry:'Reintentar',mismatch:'Las contraseñas no coinciden.',weak:'Usa al menos 6 caracteres.',failed:'No se pudo completar la solicitud. Inténtalo más tarde.',invalidCode:'Código inválido, caducado o ya utilizado.',rate:'Demasiadas solicitudes. Espera antes de reintentar.',invalidPhone:'Introduce un número válido y selecciona el país correcto.',unsupported:'Esta función no está disponible en este país.',bound:'Teléfono vinculado',unbound:'Sin teléfono vinculado',bind:'Vincular teléfono',unbind:'Desvincular teléfono',bindDone:'Teléfono vinculado.',unbindDone:'Teléfono desvinculado.',unbindHint:'Enviaremos el código al teléfono vinculado. Después podrás seguir entrando con tu usuario y contraseña.',passwordRequired:'Configura una contraseña antes de desvincular.',occupied:'El teléfono o usuario ya está en uso.',account:'La cuenta no existe o no está disponible.',requiredCode:'Solicita e introduce un código SMS.',submitting:'Procesando…',sent:'Código enviado.',inviteRequired:'Introduce un código de invitación válido.'
  },
  fr: {
    phone:'Numéro de téléphone',country:'Pays ou région',code:'Code SMS',send:'Envoyer le code',sending:'Envoi…',login:'Connexion par SMS',passwordLogin:'Connexion par mot de passe',retrieve:'Réinitialiser par SMS',emailRetrieve:'Réinitialiser par e-mail',register:'Créer un compte',username:'Nom d’utilisateur',password:'Mot de passe',confirm:'Confirmer le mot de passe',invite:'Code d’invitation',newPassword:'Nouveau mot de passe',reset:'Réinitialiser le mot de passe',resetDone:'Mot de passe réinitialisé. Reconnectez-vous.',back:'Retour à la connexion',unavailable:'Cette fonction SMS n’est pas encore disponible.',closed:'Les inscriptions sont fermées.',loadError:'Impossible de charger les paramètres d’inscription.',retry:'Réessayer',mismatch:'Les mots de passe ne correspondent pas.',weak:'Utilisez au moins 6 caractères.',failed:'Impossible de terminer la demande. Réessayez plus tard.',invalidCode:'Code invalide, expiré ou déjà utilisé.',rate:'Trop de demandes. Veuillez patienter.',invalidPhone:'Saisissez un numéro valide et sélectionnez le bon pays.',unsupported:'Cette fonction n’est pas disponible dans ce pays.',bound:'Téléphone associé',unbound:'Aucun téléphone associé',bind:'Associer le téléphone',unbind:'Dissocier le téléphone',bindDone:'Téléphone associé.',unbindDone:'Téléphone dissocié.',unbindHint:'Le code sera envoyé au téléphone associé. Vous pourrez toujours vous connecter avec votre identifiant et votre mot de passe.',passwordRequired:'Définissez un mot de passe avant de dissocier le téléphone.',occupied:'Ce téléphone ou cet identifiant est déjà utilisé.',account:'Le compte n’existe pas ou est indisponible.',requiredCode:'Demandez et saisissez un code SMS.',submitting:'Traitement…',sent:'Code envoyé.',inviteRequired:'Saisissez un code d’invitation valide.'
  },
  de: {
    phone:'Telefonnummer',country:'Land oder Region',code:'SMS-Code',send:'Code senden',sending:'Wird gesendet…',login:'Per SMS anmelden',passwordLogin:'Mit Passwort anmelden',retrieve:'Per SMS zurücksetzen',emailRetrieve:'Per E-Mail zurücksetzen',register:'Registrieren',username:'Benutzername',password:'Passwort',confirm:'Passwort bestätigen',invite:'Einladungscode',newPassword:'Neues Passwort',reset:'Passwort zurücksetzen',resetDone:'Passwort zurückgesetzt. Bitte erneut anmelden.',back:'Zurück zur Anmeldung',unavailable:'Diese SMS-Funktion ist noch nicht verfügbar.',closed:'Die Registrierung ist geschlossen.',loadError:'Registrierungseinstellungen konnten nicht geladen werden.',retry:'Erneut versuchen',mismatch:'Die Passwörter stimmen nicht überein.',weak:'Mindestens 6 Zeichen verwenden.',failed:'Anfrage fehlgeschlagen. Bitte später erneut versuchen.',invalidCode:'Code ungültig, abgelaufen oder bereits verwendet.',rate:'Zu viele Anfragen. Bitte warten.',invalidPhone:'Gültige Telefonnummer und das richtige Land angeben.',unsupported:'Diese Funktion ist in diesem Land nicht verfügbar.',bound:'Telefon verknüpft',unbound:'Kein Telefon verknüpft',bind:'Telefon verknüpfen',unbind:'Telefonverknüpfung aufheben',bindDone:'Telefon wurde verknüpft.',unbindDone:'Verknüpfung wurde aufgehoben.',unbindHint:'Der Code wird an das verknüpfte Telefon gesendet. Die Anmeldung mit Benutzername und Passwort bleibt möglich.',passwordRequired:'Vor dem Aufheben der Verknüpfung ein Passwort festlegen.',occupied:'Telefonnummer oder Benutzername wird bereits verwendet.',account:'Konto nicht vorhanden oder nicht verfügbar.',requiredCode:'Bitte zuerst einen SMS-Code anfordern und eingeben.',submitting:'Wird verarbeitet…',sent:'Code gesendet.',inviteRequired:'Gültigen Einladungscode eingeben.'
  },
  ru: {
    phone:'Номер телефона',country:'Страна или регион',code:'Код из SMS',send:'Отправить код',sending:'Отправка…',login:'Войти по SMS',passwordLogin:'Войти с паролем',retrieve:'Восстановить по SMS',emailRetrieve:'Восстановить по почте',register:'Регистрация',username:'Имя пользователя',password:'Пароль',confirm:'Подтвердите пароль',invite:'Код приглашения',newPassword:'Новый пароль',reset:'Сбросить пароль',resetDone:'Пароль изменён. Войдите снова.',back:'Вернуться ко входу',unavailable:'Эта функция SMS пока недоступна.',closed:'Регистрация закрыта.',loadError:'Не удалось загрузить настройки регистрации.',retry:'Повторить',mismatch:'Пароли не совпадают.',weak:'Используйте не менее 6 символов.',failed:'Не удалось выполнить запрос. Повторите позже.',invalidCode:'Код неверен, просрочен или уже использован.',rate:'Слишком много запросов. Подождите.',invalidPhone:'Введите верный номер и выберите нужную страну.',unsupported:'Функция недоступна в этой стране.',bound:'Телефон привязан',unbound:'Телефон не привязан',bind:'Привязать телефон',unbind:'Отвязать телефон',bindDone:'Телефон привязан.',unbindDone:'Телефон отвязан.',unbindHint:'Код будет отправлен на привязанный телефон. После отвязки можно входить по имени пользователя и паролю.',passwordRequired:'Перед отвязкой задайте пароль для входа.',occupied:'Телефон или имя пользователя уже используется.',account:'Аккаунт не существует или недоступен.',requiredCode:'Сначала запросите и введите код из SMS.',submitting:'Обработка…',sent:'Код отправлен.',inviteRequired:'Введите действительный код приглашения.'
  },
  ar: {
    phone:'رقم الهاتف',country:'البلد أو المنطقة',code:'رمز التحقق',send:'إرسال الرمز',sending:'جارٍ الإرسال…',login:'الدخول برسالة نصية',passwordLogin:'الدخول بكلمة المرور',retrieve:'الاستعادة برسالة نصية',emailRetrieve:'الاستعادة بالبريد الإلكتروني',register:'إنشاء حساب',username:'اسم المستخدم',password:'كلمة المرور',confirm:'تأكيد كلمة المرور',invite:'رمز الدعوة',newPassword:'كلمة المرور الجديدة',reset:'إعادة تعيين كلمة المرور',resetDone:'تم تغيير كلمة المرور. يرجى تسجيل الدخول مجددًا.',back:'العودة لتسجيل الدخول',unavailable:'خدمة الرسائل النصية هذه غير متاحة حاليًا.',closed:'التسجيل مغلق حاليًا.',loadError:'تعذر تحميل إعدادات التسجيل.',retry:'إعادة المحاولة',mismatch:'كلمتا المرور غير متطابقتين.',weak:'استخدم 6 أحرف على الأقل.',failed:'تعذر إكمال الطلب. حاول لاحقًا.',invalidCode:'الرمز غير صالح أو منتهي الصلاحية أو مستخدم.',rate:'طلبات كثيرة. انتظر قبل المحاولة مجددًا.',invalidPhone:'أدخل رقمًا صالحًا واختر البلد الصحيح.',unsupported:'هذه الخدمة غير متاحة في هذا البلد.',bound:'الهاتف مرتبط',unbound:'لا يوجد هاتف مرتبط',bind:'ربط الهاتف',unbind:'إلغاء ربط الهاتف',bindDone:'تم ربط الهاتف.',unbindDone:'تم إلغاء ربط الهاتف.',unbindHint:'سنرسل الرمز إلى الهاتف المرتبط. بعد إلغاء الربط يمكنك الدخول باسم المستخدم وكلمة المرور.',passwordRequired:'عيّن كلمة مرور قبل إلغاء الربط.',occupied:'رقم الهاتف أو اسم المستخدم مستخدم بالفعل.',account:'الحساب غير موجود أو غير متاح.',requiredCode:'اطلب رمز التحقق وأدخله أولًا.',submitting:'جارٍ المعالجة…',sent:'تم إرسال الرمز.',inviteRequired:'أدخل رمز دعوة صالحًا.'
  },
  pt: {
    phone:'Número de telefone',country:'País ou região',code:'Código SMS',send:'Enviar código',sending:'Enviando…',login:'Entrar por SMS',passwordLogin:'Entrar com senha',retrieve:'Redefinir por SMS',emailRetrieve:'Redefinir por e-mail',register:'Criar conta',username:'Nome de usuário',password:'Senha',confirm:'Confirmar senha',invite:'Código de convite',newPassword:'Nova senha',reset:'Redefinir senha',resetDone:'Senha redefinida. Entre novamente.',back:'Voltar ao login',unavailable:'Esta função SMS ainda não está disponível.',closed:'O cadastro está fechado.',loadError:'Não foi possível carregar as configurações de cadastro.',retry:'Tentar novamente',mismatch:'As senhas não coincidem.',weak:'Use pelo menos 6 caracteres.',failed:'Não foi possível concluir. Tente mais tarde.',invalidCode:'Código inválido, expirado ou já utilizado.',rate:'Muitas solicitações. Aguarde antes de tentar novamente.',invalidPhone:'Digite um número válido e selecione o país correto.',unsupported:'Esta função não está disponível neste país.',bound:'Telefone vinculado',unbound:'Nenhum telefone vinculado',bind:'Vincular telefone',unbind:'Desvincular telefone',bindDone:'Telefone vinculado.',unbindDone:'Telefone desvinculado.',unbindHint:'O código será enviado ao telefone vinculado. Depois, você ainda poderá entrar com seu usuário e senha.',passwordRequired:'Defina uma senha antes de desvincular.',occupied:'Telefone ou nome de usuário já em uso.',account:'A conta não existe ou está indisponível.',requiredCode:'Solicite e digite um código SMS primeiro.',submitting:'Processando…',sent:'Código enviado.',inviteRequired:'Digite um código de convite válido.'
  },
  ug: {
    phone:'تېلېفون نومۇرى',country:'دۆلەت ياكى رايون',code:'قىسقا ئۇچۇر دەلىللەش كودى',send:'كود ئەۋەتىش',sending:'ئەۋەتىلىۋاتىدۇ…',login:'قىسقا ئۇچۇر بىلەن كىرىش',passwordLogin:'پارول بىلەن كىرىش',retrieve:'قىسقا ئۇچۇر ئارقىلىق ئەسلىگە كەلتۈرۈش',emailRetrieve:'ئېلخەت ئارقىلىق ئەسلىگە كەلتۈرۈش',register:'تىزىملىتىش',username:'ئىشلەتكۈچى ئىسمى',password:'پارول',confirm:'پارولنى جەزملەشتۈرۈش',invite:'تەكلىپ كودى',newPassword:'يېڭى پارول',reset:'پارولنى قايتا بەلگىلەش',resetDone:'پارول ئۆزگەرتىلدى. قايتا كىرىڭ.',back:'كىرىش بېتىگە قايتىش',unavailable:'بۇ قىسقا ئۇچۇر ئىقتىدارى ھازىرچە ئىشلىمەيدۇ.',closed:'تىزىملىتىش تاقالغان.',loadError:'تىزىملىتىش تەڭشەكلىرىنى يۈكلىگىلى بولمىدى.',retry:'قايتا سىناش',mismatch:'پاروللار بىردەك ئەمەس.',weak:'كەم دېگەندە 6 ھەرپ كىرگۈزۈڭ.',failed:'مەشغۇلات مەغلۇپ بولدى. كېيىن قايتا سىناڭ.',invalidCode:'كود خاتا، ۋاقتى ئۆتكەن ياكى ئىشلىتىلگەن.',rate:'تەلەپ بەك كۆپ. سەل ساقلاڭ.',invalidPhone:'توغرا نومۇر كىرگۈزۈپ، توغرا دۆلەتنى تاللاڭ.',unsupported:'بۇ دۆلەتتە بۇ ئىقتىدار ئىشلىمەيدۇ.',bound:'تېلېفون باغلانغان',unbound:'تېلېفون باغلانمىغان',bind:'تېلېفون باغلاش',unbind:'تېلېفوننى ئايرىش',bindDone:'تېلېفون باغلاندى.',unbindDone:'تېلېفون ئايرىلدى.',unbindHint:'كود باغلانغان تېلېفونغا ئەۋەتىلىدۇ. ئايرىغاندىن كېيىنمۇ ئىشلەتكۈچى ئىسمى ۋە پارول بىلەن كىرەلەيسىز.',passwordRequired:'ئايرىشتىن بۇرۇن كىرىش پارولى بەلگىلەڭ.',occupied:'تېلېفون نومۇرى ياكى ئىشلەتكۈچى ئىسمى ئىشلىتىلگەن.',account:'ھېسابات يوق ياكى ئىشلەتكىلى بولمايدۇ.',requiredCode:'ئاۋۋال دەلىللەش كودى ئېلىپ كىرگۈزۈڭ.',submitting:'بىر تەرەپ قىلىنىۋاتىدۇ…',sent:'كود ئەۋەتىلدى.',inviteRequired:'ئىناۋەتلىك تەكلىپ كودى كىرگۈزۈڭ.'
  }
}
export function smsCopy(language) { return language === 'zh-TW' ? tw : language?.startsWith('zh') ? zh : translations[language] || en }
export function smsErrorText(error, copy) {
  const key = ({invalid_sms_code:'invalidCode',sms_rate_limited:'rate',invalid_phone:'invalidPhone',phone_country_code_required:'invalidPhone',country_not_supported:'unsupported',sms_not_configured:'unavailable',registration_disabled:'closed',phone_registration_disabled:'closed',phone_or_username_exists:'occupied',phone_exists:'occupied',phone_already_bound:'occupied',account_unavailable:'account',password_required_before_unbind:'passwordRequired',invalid_invite_code:'inviteRequired',invite_code_required:'inviteRequired',weak_password:'weak'})[error?.code || error?.message]
  return copy[key || 'failed']
}
